### ISSUE TITLE
更新到1.4.0后显示无权访问任何网站

### ISSUE THREAD

**Issue by jdnx** [meowtec/chrome-menufish#12]
选项里显示如此, 任何网站都没有菜单了, 貌似是升级后出现的,请作者处理,谢谢

update: 删除后重装又好了, 但是权限那里还是显示 无法访问其他网站, 不知道是啥原因

**Comment by meowtec** [comment]
截图看看？我这边没发现问题

**Comment by jdnx** [comment]
> 截图看看？我这边没发现问题

没法截图, 因为现在已经好了, 出问题时再任何网站选中文字后 不弹出 搜索菜单  配置那里显示

权限
此扩展程序无需任何特殊权限
有权访问的网站
此扩展程序无权访问其他网站。

出现问题时我看到了上面的描述, 然后看了其他 extension 貌似"有权访问的网站"那里显示为

有权访问的网站
允许此扩展程序读取和更改您在所访问的网站上留存的所有数据：
点击时
在特定网站上
在所有网站上

以为问题出在这里, 然后把 extension 删除后再装 ,过了一会就好了(网页选中文字 搜索菜单出来了), 看配置那里还是显示 无权访问,看来问题不是这个?   所以不直到问题出在哪里

**Comment by meowtec** [comment]
我也不太清楚，以前是有这类权限的，当时有个网站主页，为了网站和扩展联动就加了点权限。
但是后面网站主页早就下线了，这次更新就去掉了相关的逻辑，就不需要权限了。

你遇到问题，可能是因为旧版本（需要权限）升级新版本（不需要权限）Chrome 有点 BUG。
