### ISSUE TITLE
chrome应用商店开始提示“此扩展程序未遵循 Chrome 扩展程序的最佳实践，因此可能很快将不再受支持。”

### ISSUE THREAD

**Issue by 453974158** [meowtec/chrome-menufish#29]
chrome应用商店开始提示“此扩展程序未遵循 Chrome 扩展程序的最佳实践，因此可能很快将不再受支持。”

**Comment by meowtec** [comment]
已经升级到 manifest v3 和最新的 API
旧的配置项可能会丢失，最好重新配置一下
