### ISSUE TITLE
更新后文字搜索打开的标签总是在最后一个标签位置新建的问题

### ISSUE THREAD

**Issue by leonvxe** [meowtec/chrome-menufish#32]
更新前，文字搜索会在被搜索的标签右侧新建标签搜索，更新后则变成在最后一个标签位置新建的问题。尝试了自带的搜索和其他的搜索插件新建标签位置也是在被搜索的标签右侧新建标签搜索，请问是更新导致的吗，如何解决。

**Comment by meowtec** [comment]
应该是，我需要看看
