### ISSUE TITLE
能否加一个如果是隐身模式 就在当前的隐身模式窗口打开网页而不是新开一个非隐身模式的呢

### ISSUE THREAD

**Issue by anonymou3** [meowtec/chrome-menufish#6]

**Comment by meowtec** [comment]
隐身模式也能使用扩展吗？不能够吧

**Comment by anonymou3** [comment]
你好这样是可以的 可以在扩展里设置，我平时全使用的是隐身模式，扩展也基本都能使用



在 2019-08-10 14:15:57，"Berton Zhu" <notifications@github.com> 写道：

隐身模式也能使用扩展吗？不能够吧

**Comment by meowtec** [comment]
https://github.com/meowtec/chrome-menufish/pull/11
