### ISSUE TITLE
能增加分享功能开关吗

### ISSUE THREAD

**Issue by aitianci** [meowtec/chrome-menufish#9]
我不需要分享功能，就删除了所有分享url，之后发现分享功能仍存在于右键，但不起作用。

我觉得这种情况下不显示这个选项更合理。或者直接增加一个可以一键关闭显示分享功能的开关。

![image](https://user-images.githubusercontent.com/10165845/82834196-afe2b080-9ec0-11ea-82b9-f1cbe3916036.png)

**Comment by meowtec** [comment]
https://github.com/meowtec/chrome-menufish/pull/11
